allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  vue-demi: set this to true or false
minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.42'
  - '@vue/compiler-dom@3.5.42'
  - '@vue/compiler-sfc@3.5.42'
  - '@vue/compiler-ssr@3.5.42'
  - '@vue/reactivity@3.5.42'
  - '@vue/runtime-core@3.5.42'
  - '@vue/runtime-dom@3.5.42'
  - '@vue/server-renderer@3.5.42'
  - '@vue/shared@3.5.42'
  - vue-router@5.3.0
  - vue@3.5.42
